# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Get main SHA
      run: export MAIN_BRANCH_SHA=$(git rev-parse main)

    - name: Cache the built for react-scripts
      uses: actions/cache@v2
      with:
        path: ./build
        key: build-assets-${{ github.sha }}
        restore-keys: |
          build-assets-${{ env.MAIN_BRANCH_SHA }}

    - run: yarn
    - run: yarn build
